python "%SUMO_HOME%\tools\ptlines2flows.py" -n osm.net.xml.gz -e 3600 -p 600 --random-begin --seed 42 --ptstops osm_stops.add.xml --ptlines osm_ptlines.xml -o osm_pt.rou.xml --ignore-errors --vtype-prefix pt_ --stopinfos-file stopinfos.xml --routes-file vehroutes.xml --trips-file trips.trips.xml --min-stops 0 --extend-to-fringe --verbose
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml.gz --fringe-factor 1 --insertion-density 20 -o osm.pedestrian.trips.xml -r osm.pedestrian.rou.xml -e 3600 --vehicle-class pedestrian --prefix ped --persontrips --trip-attributes "modes=\"public\"" --additional-files osm_stops.add.xml,osm_pt.rou.xml --persontrip.walk-opposite-factor 0.8
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml.gz --fringe-factor 2 --insertion-density 20 -o osm.bicycle.trips.xml -r osm.bicycle.rou.xml -e 3600 --trip-attributes "departLane=\"best\"" --fringe-start-attributes "departSpeed=\"max\"" --validate --remove-loops --vehicle-class bicycle --vclass bicycle --prefix bike --max-distance 8000
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml.gz --fringe-factor 2 --insertion-density 20 -o osm.motorcycle.trips.xml -r osm.motorcycle.rou.xml -e 3600 --trip-attributes "departLane=\"best\"" --fringe-start-attributes "departSpeed=\"max\"" --validate --remove-loops --vehicle-class motorcycle --vclass motorcycle --prefix motorcycle --max-distance 1200
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml.gz --fringe-factor 5 --insertion-density 20 -o osm.bus.trips.xml -r osm.bus.rou.xml -e 3600 --trip-attributes "departLane=\"best\"" --fringe-start-attributes "departSpeed=\"max\"" --validate --remove-loops --vehicle-class bus --vclass bus --prefix bus --min-distance 600 --min-distance.fringe 10
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml.gz --fringe-factor 5 --insertion-density 20 -o osm.truck.trips.xml -r osm.truck.rou.xml -e 3600 --trip-attributes "departLane=\"best\"" --fringe-start-attributes "departSpeed=\"max\"" --validate --remove-loops --vehicle-class truck --vclass truck --prefix truck --min-distance 600 --min-distance.fringe 10
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml.gz --fringe-factor 5 --insertion-density 30 -o osm.passenger.trips.xml -r osm.passenger.rou.xml -e 3600 --trip-attributes "departLane=\"best\"" --fringe-start-attributes "departSpeed=\"max\"" --validate --remove-loops --vehicle-class passenger --vclass passenger --prefix veh --min-distance 300 --min-distance.fringe 10 --allow-fringe.min-length 1000 --lanes
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml.gz --fringe-factor 20 --insertion-density 2 -o osm.tram.trips.xml -r osm.tram.rou.xml -e 3600 --trip-attributes "departLane=\"best\"" --fringe-start-attributes "departSpeed=\"max\"" --validate --remove-loops --vehicle-class tram --vclass tram --prefix tram --min-distance 1200 --min-distance.fringe 10
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml.gz --fringe-factor 40 --insertion-density 2 -o osm.rail.trips.xml -r osm.rail.rou.xml -e 3600 --trip-attributes "departLane=\"best\"" --fringe-start-attributes "departSpeed=\"max\"" --validate --remove-loops --vehicle-class rail --vclass rail --prefix rail --min-distance 2400 --min-distance.fringe 10
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml.gz --fringe-factor 40 --insertion-density 2 -o osm.rail_urban.trips.xml -r osm.rail_urban.rou.xml -e 3600 --trip-attributes "departLane=\"best\"" --fringe-start-attributes "departSpeed=\"max\"" --validate --remove-loops --vehicle-class rail_urban --vclass rail_urban --prefix rail_urban --min-distance 1800 --min-distance.fringe 10
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml.gz --fringe-factor 40 --insertion-density 2 -o osm.ship.trips.xml -r osm.ship.rou.xml -e 3600 --vehicle-class ship --vclass ship --prefix ship --fringe-start-attributes "departSpeed=\"max\"" --validate
